"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InputDataType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputDataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputDataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IMAGE: _InputDataType.ValueType  # 0
    VIDEO: _InputDataType.ValueType  # 1
    AUDIO: _InputDataType.ValueType  # 2
    TEXT: _InputDataType.ValueType  # 3
    TEST: _InputDataType.ValueType  # 4

class InputDataType(_InputDataType, metaclass=_InputDataTypeEnumTypeWrapper): ...

IMAGE: InputDataType.ValueType  # 0
VIDEO: InputDataType.ValueType  # 1
AUDIO: InputDataType.ValueType  # 2
TEXT: InputDataType.ValueType  # 3
TEST: InputDataType.ValueType  # 4
global___InputDataType = InputDataType

class _InputRepresentation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputRepresentationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputRepresentation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CAR: _InputRepresentation.ValueType  # 0

class InputRepresentation(_InputRepresentation, metaclass=_InputRepresentationEnumTypeWrapper): ...

CAR: InputRepresentation.ValueType  # 0
global___InputRepresentation = InputRepresentation

class _InputDomain:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputDomainEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputDomain.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCIENTIFIC: _InputDomain.ValueType  # 0

class InputDomain(_InputDomain, metaclass=_InputDomainEnumTypeWrapper): ...

SCIENTIFIC: InputDomain.ValueType  # 0
global___InputDomain = InputDomain

class _OutputDataType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OutputDataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OutputDataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BOUNDINGBOX: _OutputDataType.ValueType  # 0
    LABEL: _OutputDataType.ValueType  # 1

class OutputDataType(_OutputDataType, metaclass=_OutputDataTypeEnumTypeWrapper): ...

BOUNDINGBOX: OutputDataType.ValueType  # 0
LABEL: OutputDataType.ValueType  # 1
global___OutputDataType = OutputDataType

class _OutputRepresentation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OutputRepresentationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OutputRepresentation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FACE: _OutputRepresentation.ValueType  # 0

class OutputRepresentation(_OutputRepresentation, metaclass=_OutputRepresentationEnumTypeWrapper): ...

FACE: OutputRepresentation.ValueType  # 0
global___OutputRepresentation = OutputRepresentation

@typing_extensions.final
class Query(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Audio(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AUDIO_FIELD_NUMBER: builtins.int
        audio: builtins.bytes
        def __init__(
            self,
            *,
            audio: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["audio", b"audio"]) -> None: ...

    @typing_extensions.final
    class Image(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IMAGE_FIELD_NUMBER: builtins.int
        image: builtins.bytes
        def __init__(
            self,
            *,
            image: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["image", b"image"]) -> None: ...

    @typing_extensions.final
    class Video(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VIDEO_FIELD_NUMBER: builtins.int
        video: builtins.bytes
        def __init__(
            self,
            *,
            video: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["video", b"video"]) -> None: ...

    @typing_extensions.final
    class Text(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEXT_FIELD_NUMBER: builtins.int
        text: builtins.str
        def __init__(
            self,
            *,
            text: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["text", b"text"]) -> None: ...

    AUDIO_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    VIDEO_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    @property
    def audio(self) -> global___Query.Audio: ...
    @property
    def image(self) -> global___Query.Image: ...
    @property
    def video(self) -> global___Query.Video: ...
    @property
    def text(self) -> global___Query.Text: ...
    def __init__(
        self,
        *,
        audio: global___Query.Audio | None = ...,
        image: global___Query.Image | None = ...,
        video: global___Query.Video | None = ...,
        text: global___Query.Text | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["audio", b"audio", "image", b"image", "q", b"q", "text", b"text", "video", b"video"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["audio", b"audio", "image", b"image", "q", b"q", "text", b"text", "video", b"video"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["q", b"q"]) -> typing_extensions.Literal["audio", "image", "video", "text"] | None: ...

global___Query = Query

@typing_extensions.final
class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Label(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LABEL_FIELD_NUMBER: builtins.int
        SCORE_FIELD_NUMBER: builtins.int
        label: builtins.str
        score: builtins.float
        def __init__(
            self,
            *,
            label: builtins.str = ...,
            score: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["label", b"label", "score", b"score"]) -> None: ...

    @typing_extensions.final
    class BoundingBoxBox(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        XMIN_FIELD_NUMBER: builtins.int
        XMAX_FIELD_NUMBER: builtins.int
        YMIN_FIELD_NUMBER: builtins.int
        YMAX_FIELD_NUMBER: builtins.int
        xmin: builtins.float
        xmax: builtins.float
        ymin: builtins.float
        ymax: builtins.float
        def __init__(
            self,
            *,
            xmin: builtins.float = ...,
            xmax: builtins.float = ...,
            ymin: builtins.float = ...,
            ymax: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["xmax", b"xmax", "xmin", b"xmin", "ymax", b"ymax", "ymin", b"ymin"]) -> None: ...

    @typing_extensions.final
    class BoundingBox(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BOX_FIELD_NUMBER: builtins.int
        LABEL_FIELD_NUMBER: builtins.int
        SCORE_FIELD_NUMBER: builtins.int
        @property
        def box(self) -> global___Result.BoundingBoxBox: ...
        label: builtins.str
        score: builtins.float
        def __init__(
            self,
            *,
            box: global___Result.BoundingBoxBox | None = ...,
            label: builtins.str = ...,
            score: builtins.float = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["box", b"box"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["box", b"box", "label", b"label", "score", b"score"]) -> None: ...

    @typing_extensions.final
    class SpeechRecognitionChunk(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEXT_FIELD_NUMBER: builtins.int
        TIMESTAMPS_FIELD_NUMBER: builtins.int
        text: builtins.str
        @property
        def timestamps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        def __init__(
            self,
            *,
            text: builtins.str = ...,
            timestamps: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["text", b"text", "timestamps", b"timestamps"]) -> None: ...

    @typing_extensions.final
    class SpeechRecognition(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEXT_FIELD_NUMBER: builtins.int
        text: builtins.str
        """optional repeated chunks SpeechRecognitionChunk = 2;"""
        def __init__(
            self,
            *,
            text: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["text", b"text"]) -> None: ...

    @typing_extensions.final
    class Mask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SCORE_FIELD_NUMBER: builtins.int
        LABEL_FIELD_NUMBER: builtins.int
        score: builtins.float
        label: builtins.str
        """repeated repeated int32 mask = 3;"""
        def __init__(
            self,
            *,
            score: builtins.float = ...,
            label: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["label", b"label", "score", b"score"]) -> None: ...

    @typing_extensions.final
    class TokenMask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SCORE_FIELD_NUMBER: builtins.int
        TOKEN_FIELD_NUMBER: builtins.int
        score: builtins.float
        token: builtins.str
        def __init__(
            self,
            *,
            score: builtins.float = ...,
            token: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["score", b"score", "token", b"token"]) -> None: ...

    @typing_extensions.final
    class TokenNER(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GROUP_FIELD_NUMBER: builtins.int
        SCORE_FIELD_NUMBER: builtins.int
        WORD_FIELD_NUMBER: builtins.int
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        group: builtins.str
        score: builtins.float
        word: builtins.str
        start: builtins.int
        end: builtins.int
        def __init__(
            self,
            *,
            group: builtins.str = ...,
            score: builtins.float = ...,
            word: builtins.str = ...,
            start: builtins.int = ...,
            end: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "group", b"group", "score", b"score", "start", b"start", "word", b"word"]) -> None: ...

    @typing_extensions.final
    class Answer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SCORE_FIELD_NUMBER: builtins.int
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        ANSWER_FIELD_NUMBER: builtins.int
        score: builtins.float
        start: builtins.int
        end: builtins.int
        answer: builtins.str
        def __init__(
            self,
            *,
            score: builtins.float = ...,
            start: builtins.int = ...,
            end: builtins.int = ...,
            answer: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["answer", b"answer", "end", b"end", "score", b"score", "start", b"start"]) -> None: ...

    @typing_extensions.final
    class TableAnswer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ANSWER_FIELD_NUMBER: builtins.int
        answer: builtins.str
        """TODO"""
        def __init__(
            self,
            *,
            answer: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["answer", b"answer"]) -> None: ...

    LABEL_FIELD_NUMBER: builtins.int
    BOUNDINGBOX_FIELD_NUMBER: builtins.int
    OTHER_FIELD_NUMBER: builtins.int
    @property
    def label(self) -> global___Result.Label: ...
    @property
    def boundingbox(self) -> global___Result.BoundingBox: ...
    other: builtins.str
    def __init__(
        self,
        *,
        label: global___Result.Label | None = ...,
        boundingbox: global___Result.BoundingBox | None = ...,
        other: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["boundingbox", b"boundingbox", "label", b"label", "r", b"r"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boundingbox", b"boundingbox", "label", b"label", "other", b"other", "r", b"r"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["r", b"r"]) -> typing_extensions.Literal["label", "boundingbox"] | None: ...

global___Result = Result

@typing_extensions.final
class Input(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_TYPE_FIELD_NUMBER: builtins.int
    REPRESENTATION_FIELD_NUMBER: builtins.int
    data_type: global___InputDataType.ValueType
    representation: global___InputRepresentation.ValueType
    def __init__(
        self,
        *,
        data_type: global___InputDataType.ValueType = ...,
        representation: global___InputRepresentation.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_type", b"data_type", "representation", b"representation"]) -> None: ...

global___Input = Input

@typing_extensions.final
class Output(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_TYPE_FIELD_NUMBER: builtins.int
    REPRESENTATION_FIELD_NUMBER: builtins.int
    data_type: global___OutputDataType.ValueType
    representation: global___OutputRepresentation.ValueType
    def __init__(
        self,
        *,
        data_type: global___OutputDataType.ValueType = ...,
        representation: global___OutputRepresentation.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_type", b"data_type", "representation", b"representation"]) -> None: ...

global___Output = Output

@typing_extensions.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MODEL_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    model_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        model_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "model_name", b"model_name"]) -> None: ...

global___Task = Task
